services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/docker-compose
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  mongo-data:
